name: "Validate"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  hassfest:
    name: "Hassfest"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # Version 7.0.0

      - name: "Run hassfest validation"
        uses: home-assistant/actions/hassfest@868e6cb4607727d764341a158d98872cd63fa658 # Version 11 September 2025

  hacs:
    name: "HACS"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # Version 7.0.0

      - name: "Run HACS validation"
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # Version 22.5.0
        with:
          category: "integration"
